### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by Python3-8** [SwirlLang/Swirl#13]
I was eager to try out Swirl, so I went to the [docs](https://swirl-lang.vercel.app/docs/) and to the [installation section](https://swirl-lang.vercel.app/docs/getting-started/installation) and tried installing Swirl with `brew install Swirl`. I keep getting this error:

![swirl-error](https://user-images.githubusercontent.com/66139317/175593758-da1a5529-5522-4fb7-b927-01af1818b028.png)

Is there something I'm missing?

**Comment by In-diaonic** [comment]
Sorry, Swirl isn't released yet, we are hoping to releasing the first public beta version by the end of August this year. Cheers.

**Comment by MrinmoyHaloi** [comment]
The docs are just prototypes. Its for testing purposes.

**Comment by MrinmoyHaloi** [comment]
Sorry for the inconvenience caused,

**Comment by 0x454d505459** [comment]
> I was eager to try out Swirl, so I went to the [docs](https://swirl-lang.vercel.app/docs/) and to the [installation section](https://swirl-lang.vercel.app/docs/getting-started/installation) and tried installing Swirl with `brew install Swirl`. I keep getting this error:
> 
> ![swirl-error](https://user-images.githubusercontent.com/66139317/175593758-da1a5529-5522-4fb7-b927-01af1818b028.png)
> 
> Is there something I'm missing?

Swirl is in really early dev right now, the lang is not ready to be published to the aur, nor brew.
But if you still want to have a compiled version, here is how you can do it:
 1) clone the repo: `git clone https://github.com/SwirlLang/Swirl.git` (or download as a zip)
 2) prepare the build using cmake: `cmake CMakeLists.txt`
 3) build using make: `make`
 
 The compiler isn't done yet, and so you can't do anything with right now
 
 Cheers.

**Comment by Python3-8** [comment]
Thanks for the clarification, I'm excited to try out Swirl someday!

**Comment by In-diaonic** [comment]
> Thanks for the clarification, I'm excited to try out Swirl someday!

Good to know :)

**Comment by Python3-8** [comment]
By the way, I just looked through a tiny bit of the source code, and I love how Swirl is similar to a compiled Python. This opens up a whole new door of opportunities for Python programmers like me.

**Comment by In-diaonic** [comment]
> By the way, I just looked through a tiny bit of the source code, and I love how Swirl is similar to a compiled Python. This opens up a whole new door of opportunities for Python programmers like me.

Yeah python's simplicity and powerful nature works as an inspiration for us, however Swirl will be approximately more than 11 times faster than python.
