### ISSUE TITLE
Transpiler doesn't include built-ins

### ISSUE THREAD

**Issue by Pranjal-Patel** [SwirlLang/Swirl#21]
The generated C++ code is incorrect

File `main.sw`
```py
print("Hello World")
```
The generated `main.cpp` file in `__swirl_cache__`:
```c++
int main() {
print("Hello World");}
```
![image](https://user-images.githubusercontent.com/85670037/209428598-e2bd99de-ac9f-4983-a6fd-6abe4fda0ab4.png)

same with
```rs
if true {
	print("Hello")
} else {
	print("Bye")
}
```
Generated C++ code:
(missing `}`)
```c++
int main() {
if (true ){print("Hello");}else{print("Bye");}
```
![image](https://user-images.githubusercontent.com/85670037/209428571-ad462ec3-7357-4b4b-9db3-c6caa9126b55.png)

-   OS: windows 11
-   Swirl version: v0.0.2-alpha

**Comment by 0x454d505459** [comment]
Just test on linux (I don't have windows running rn) and the generated code looks correct for printing "hello world" as the print template is defined in the cache
```cpp

#include <iostream>

#define elif else if

template < typename Const >
void print(Const __Obj, const std::string& __End = "\n", bool __Flush = true) {
    if (__Flush) std::cout << __Obj << __End << std::flush;
    else std::cout << __Obj << __End;
}

std::string input(std::string __Prompt) {
    std::string ret;
    std::cout << __Prompt << std::flush;
    std::getline(std::cin, ret);

    return ret;
}
int main() {
print("Hello world !!!");}
```

**Comment by 0x454d505459** [comment]
The conditional also works as intended on linux. So it is weird that this only happens on windows. Note that our primary developing platform is linux.

The generated c++ code
```cpp
#include <iostream>

#define elif else if

template < typename Const >
void print(Const __Obj, const std::string& __End = "\n", bool __Flush = true) {
    if (__Flush) std::cout << __Obj << __End << std::flush;
    else std::cout << __Obj << __End;
}

std::string input(std::string __Prompt) {
    std::string ret;
    std::cout << __Prompt << std::flush;
    std::getline(std::cin, ret);

    return ret;
}
int main() {
if (true ){print("Hello");}else{print("Bye");}}

```

**Comment by 0x454d505459** [comment]
I tested in my windows partition and looks like the issue comes from the compiled binary we released, building swirl from mysys2 it works fine. Have you tried building it yourself ? See the docs to [compile it from source](https://swirl-lang.vercel.app/docs/developers).
